### ISSUE TITLE
Hang when analyzing ELF

### ISSUE THREAD

**Issue by 20urc3** [revng/revng-c#24]
Hi there.
I tested several relatively small elf target  (tar, 7zip, etc) on two different machine (Debian 12 AMD 7950X3D 128go RAM | Kali i7 12-core 64go ram) but the analyze never stop and can run for literal hours.
Here below the trace:

```bash
[orchestra] s0urc3@Nebuchadnezzar:~/7zip$ revng artifact         --analyze         --progress         decompile-to-single-file         7zzG         | revng ptml --color         | grep -A2 -B1 '[^_]main\b'         > decompiled.c



[>                                      ]   0%     0.00s LLVM passes on root.bb.0x801b90:Code_x86_64_cloned (17)
[======>                                ]  16%  9280.07s DetectABI (6): preliminaryFunctionAnalysis
[===============>                       ]  40%  9281.76s Run module passes (5): ABI Detection Pass
[>                                      ]   0%  9281.76s Run module pass managers (1): MPM index: 0
[=============>                         ]  33% 13172.96s Analysis execution (3): Run analysis
[=========================>             ]  66% 13184.34s Analysis list revng-initial-auto-analysis (5): detect-abi
[============>                          ]  33% 13184.34s Run analyses lists (2): revng-initial-auto-analysis
[======>                                ]  16% 13184.34s revng-artifact (2): Run analyses
1
```

**Comment by pfez** [comment]
Weird. Could you please attach the smallest binary that causes this so we can investigate?

**Comment by 20urc3** [comment]
Hey, sorry but I just mentioned a few example in my initial message. You can try on 7zip, tar, objdump, whatever :)

**Comment by pfez** [comment]
I know but it's very important to use the exact same binary. If we use even a slightly different one we may not be able to reproduce the problem, and waste your time and ours.

From packages.debian.org, [this](https://packages.debian.org/bookworm/amd64/tar/download) this should be the `tar` of your debian 12. Can you confirm?

Otherwise please just send the binary.

**Comment by 20urc3** [comment]
Hey, sure I agree the thing is that this error is produced with any binary for me really that's why I didn't bother linking files. Yes I confirm it's this tar version :)

I followed the instruction described here in order to install revng: https://docs.rev.ng/user-manual/working-environment/

**Comment by pfez** [comment]
Thanks! I'll try and take a look when I have some time.

But IIUC you're saying that all the ELF binaries you tried from a regular Debian 12 amd64 distro are giving you the same problem. Correct?

That's very weird, we do mass testing on Ubuntu binaries, and I can't imagine Debian binaries to be that much different :thinking: 
I definitely have to take a look at this.

**Comment by 20urc3** [comment]
Yes, except the extremely small example provided on the website (return * 3) all the rest of the targets I tried just failed.

Let me know if you need help testing stuff :)
Cheers

**Comment by pfez** [comment]
I just tried and I couldn't reproduce this on the Debian `tar` binary you confirmed (attached as tar.gz for convenience). It runs to completion without errors.

Can you please try the following?

1. double check again that it's the same `tar` executable that caused you problems in the first place.
2. try again to reproduce on the latest `develop` branches of `revng` and `revng-c`

Thanks a lot.


[tar.tar.gz](https://github.com/user-attachments/files/15543722/tar.tar.gz)

**Comment by pfez** [comment]
Also probably unrelated @20urc3 but what distro are you using? We've had situations in the past where some bugs were easier to reproduce on some distros than others.

**Comment by 20urc3** [comment]
Hi,
I just re-installed a Debian 12 and followed those instructions for the installation:

```
$ curl -L -s https://rev.ng/downloads/revng-distributable/master/install.sh | bash
$ cd revng
$ source ./environment
```

Then I tried the following command to analyze the binary file:
`revng artifact   --analyze    --progress     decompile-to-single-file     7zzG      |  revng ptml --color     |  grep -A2 -B1 '[^_]main\b'   > decompiled.c`

**Comment by 20urc3** [comment]
What is weird is I see almost no CPU usage during "analysis''
![image](https://github.com/revng/revng-c/assets/94982366/0494812b-0c22-4eb8-9d44-b2985beac3ed)

**Comment by pfez** [comment]
Yeah I suspect it might be related to the fact that it's trying to fetch debug symbols. I'll try and check this.

Meanwhile you can try to add `--debug-info=no` to the same `revng artifact` command line, and see if it goes past the point where it hangs. If the problem is caused by it trying to fetch debug info it should work.

**Comment by aleclearmind** [comment]
@20urc3 Please attach one specific binary that's giving you problems.

**Comment by 20urc3** [comment]
Never mind, good luck folks.
