### ISSUE TITLE
Missing revngConfig.cmake file.

### ISSUE THREAD

**Issue by egberts** [revng/revng-c#7]
Missing some files during `cmake` on this platform:

```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

the error output is
```
$ ls
CMakeLists.txt  lib      LICENSE      README.md  tests
include         libexec  LICENSE.mit  share      tools
~/work/reverse-eng/revng/revng-c$ mkdir build
~/work/reverse-eng/revng/revng-c$ cd build
~/work/reverse-eng/revng/revng-c/build$ cmake ..
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "Findrevng.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "revng", but
  CMake did not find one.

  Could not find a package configuration file provided by "revng" with any of
  the following names:

    revngConfig.cmake
    revng-config.cmake

  Add the installation prefix of "revng" to CMAKE_PREFIX_PATH or set
  "revng_DIR" to a directory containing one of the above files.  If "revng"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "work/revng/revng-c/build/CMakeFiles/CMakeOutput.log".
```

**Comment by aleclearmind** [comment]
You need orchestra in order to build revng. Please [read the docs](https://docs.rev.ng/user-manual/working-environment/).

Feel free to reopen if you still have issues.

**Comment by egberts** [comment]
Tryng to do a complete rebuild without 'curl'.  Nobody sane in InfoSec trusts a download shell and execute directly.

Also, I have no Github privilege to re-open an issue in this repository.

**Comment by aleclearmind** [comment]
The docs [describes how to build from source](https://docs.rev.ng/user-manual/working-environment/#installing-revng-as-a-developer).

Please open a new issue with a specific problem following one of the supported configurations.

> Tryng to do a complete rebuild without 'curl'. Nobody sane in InfoSec trusts a download shell and execute directly.

I agree. That's why we build everything from source, and you can do it too, but that requires orchestra.

**Comment by egberts** [comment]
So we cannot build unless we have an instance of AWS platform, correct?

**Comment by aleclearmind** [comment]
Absolutely not. We just depend on the AWS SDK as an S3 client. We use it to do certain things in the cloud.
In no way shape or form we depend on anything AWS specific or make assumption on where rev.ng is running.
